### ISSUE TITLE
Why you concatenation two kinds of score map in the focal loss?

### ISSUE THREAD

**Issue by jam-cc** [zqhang/AnomalyCLIP#1]
I have noticed this operation in section 3.3, can the score map after concat still calculate the loss normally? What is the purpose of this?

**Comment by zqhang** [comment]
The corresponding elements in Sn and Sa are the probabilities for normality and abnormality according to Equation (1), where we can use focal loss to further optimize learnable parameters. The reason we use focal loss is to address the class imbalance because the anomaly regions are typically smaller than the normal ones, as mentioned in Section 3.3.
